# Generated by Django 4.1.5 on 2023-02-09 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='submissionDate',
            new_name='submission_date',
        ),
    ]
