# Generated by Django 4.1.5 on 2023-02-09 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adoptions', '0002_rename_submissiondate_pet_submission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='vaccination',
            new_name='vaccinations',
        ),
    ]
